### PR TITLE
fix: markup in banners

### LINKED ISSUE #238: HTML in information card
Some information cards have some HTML markup mixed with their content, this is probably a remnant of replacing icons.

Image

### LINKED ISSUE #241: Checkbox update inside banner not working
When creating a certificate users have found that the confirmation checkbox, which resides within an information banner, isn't enabling the corresponding button, effectively making this process impossible to conclude.

Current error:
Image

Expected behavior:
Image

### PR DESCRIPTION
**Pull request by toni-santos**
Closes #238 #241

### CODE REVIEW

File: content-scripts/modules/icons/index.tsx [hunk 1]
```diff
@@ -180,16 +180,15 @@ const replaceBgImages = (): void => {
...
-            const icon = (
-                <span
-                    className={`se-icon ri-${v}-fill`}
-                    style={{ fontSize: "1.5em" }}
-                />
-            );
-            i.replaceChildren(icon, span);
+            const icon = document.createElement("span");
+            icon.className = `se-icon ri-${v}-fill`;
+            icon.style.fontSize = "1.5em";
```
Comment (thePeras) [inline content-scripts/modules/icons/index.tsx]: you remove the commented and didn't use <Icon> component 😮

Comment (JaimeFRF) [reply content-scripts/modules/icons/index.tsx]: fixed

**Review by thePeras — APPROVED** [review]
Well done! ✅ 🛫
